version: '3.1'

services:

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Welcome@1
      MYSQL_USER: nandharam09
      MYSQL_PASSWORD: Welcome@1
      MYSQL_DATABASE: SECTOR27  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
