FROM ubuntu:latest
MAINTAINER Nandha Ram "nandhavignesh2009@gmail.com"
RUN apt-get update -y && apt-get upgrade -y && apt-get install apt-utils -y
RUN apt-get install software-properties-common -y && apt-get install network-manager -y
EXPOSE 80/tcp
RUN useradd -m -d /home/nandha nandha
RUN apt-get install nginx -y
RUN mkdir /nandha && mkdir /demo
RUN touch index.html 
COPY index.html /nandha
ADD https://www.free-css.com/assets/files/free-css-templates/download/page248/cube.zip /nandha
WORKDIR /demo
ADD https://www.free-css.com/assets/files/free-css-templates/download/page248/cube.zip .
ENTRYPOINT service nginx start && bash
USER nandha
RUN mkdir /home/nandha/nandhavignesh2009
USER root
